In [1]:
import pandas as pd 
import numpy as np

In [2]:
employees = {
    "Employee_ID": [
        101,102,103,104,105,106,107,108,109,110,
        111,112,113,114,115,116,117,118,119,120,
        120,115
    ],

    "Name": [
        "Alice"," Bob","Charlie ","David","Eva",
        "Frank","Grace","Henry","Isabella","Jack",
        "kate","LUCAS","Mia","Noah","Olivia",
        "Peter","Quinn","Rachel","Sam","Tom",
        "Tom","Olivia"
    ],

    "Age": [
        25,"26","Twenty Seven",31,None,
        28,45,-5,200,34,
        "",29,30,"N/A",27,
        41,39,33,29,31,
        31,27
    ],

    "Gender": [
        "Male","Female","female","MALE","F",
        "M","Female","Male","female","Male",
        "Female","Male","Female","Unknown","male",
        "Female","M","F","Male","Female",
        "Female","Female"
    ],

    "Department": [
        "HR","IT","Finance","Sales","IT",
        "hr","Finance ","Marketing","Sales","IT",
        "Finance","IT","Marketing","HR","Sales",
        "Finance","IT","Marketing","HR","Sales",
        "Sales","Sales"
    ],

    "Salary": [
        "50000","₹60,000",70000,"80000","N/A",
        "-5000","120000","90000","₹75,000",None,
        "65000","55,000","85000","70000","",
        "$95000","100000","110000","78000","82000",
        "82000",""
    ],

    "Joining_Date": [
        "2020-01-15",
        "15/02/2021",
        "March 3, 2022",
        "2021/04/01",
        "",
        "05-06-2020",
        None,
        "2023-12-11",
        "11/11/2022",
        "2020-07-30",
        "2019-05-14",
        "2022-13-01",
        "2021-02-28",
        "Unknown",
        "2024-01-01",
        "2018/09/15",
        "2020.10.10",
        "2023/03/07",
        "07 Aug 2022",
        "2021-06-18",
        "2021-06-18",
        "2024-01-01"
    ],

    "Email": [
        "alice@example.com",
        "bob@example",
        "charlie@gmail.com",
        "",
        None,
        "frank@yahoo.com",
        "grace@gmail.com",
        "henry@gmail",
        "isabella@gmail.com",
        "jack@gmail.com",
        "kate@gmail.com",
        "lucas@gmail.com",
        "mia@gmail.com",
        "noahgmail.com",
        "olivia@gmail.com",
        "peter@gmail.com",
        "quinn@gmail.com",
        "rachel@gmail.com",
        "sam@gmail.com",
        "tom@gmail.com",
        "tom@gmail.com",
        "olivia@gmail.com"
    ],

    "Phone": [
        "9876543210",
        "(987)-654-3211",
        "98765 43212",
        "+91-9876543213",
        "",
        None,
        "9876543215",
        "98765432",
        "9876543217",
        "9876543218",
        "9876543219",
        "9876543220",
        "9876543221",
        "Unknown",
        "9876543223",
        "9876543224",
        "9876543225",
        "9876543226",
        "9876543227",
        "9876543228",
        "9876543228",
        "9876543223"
    ],

    "Performance_Rating": [
        5,4,3,None,
        "Excellent",
        2,5,1,"4","",
        3,4,5,"N/A",2,
        4,5,3,2,1,
        1,2
    ],

    "Remote": [
        "Yes","No","YES","NO",
        True,False,
        "yes","no",
        "Y","N",
        None,
        "",
        "True",
        "False",
        "Yes",
        "No",
        True,
        False,
        "YES",
        "NO",
        "NO",
        "Yes"
    ]
}

In [3]:
df = pd.DataFrame(employees)

In [4]:
df.head()

,Employee_ID,Name,Age,Gender,Department,Salary,Joining_Date,Email,Phone,Performance_Rating,Remote
0,101,Alice,25,Male,HR,50000,2020-01-15,alice@example.com,9876543210,5,Yes
1,102,Bob,26,Female,IT,"₹60,000",15/02/2021,bob@example,(987)-654-3211,4,No
2,103,Charlie,Twenty Seven,female,Finance,70000,"March 3, 2022",charlie@gmail.com,98765 43212,3,YES
3,104,David,31,MALE,Sales,80000,2021/04/01,,+91-9876543213,None,NO
4,105,Eva,None,F,IT,N/A,,None,,Excellent,True

In [6]:
df.drop_duplicates(inplace = True)

In [7]:
df.head()

,Employee_ID,Name,Age,Gender,Department,Salary,Joining_Date,Email,Phone,Performance_Rating,Remote
0,101,Alice,25,Male,HR,50000,2020-01-15,alice@example.com,9876543210,5,Yes
1,102,Bob,26,Female,IT,"₹60,000",15/02/2021,bob@example,(987)-654-3211,4,No
2,103,Charlie,Twenty Seven,female,Finance,70000,"March 3, 2022",charlie@gmail.com,98765 43212,3,YES
3,104,David,31,MALE,Sales,80000,2021/04/01,,+91-9876543213,None,NO
4,105,Eva,None,F,IT,N/A,,None,,Excellent,True

In [8]:
df["Gender"] = df["Gender"].str.title()

In [10]:
df.head(20)

,Employee_ID,Name,Age,Gender,Department,Salary,Joining_Date,Email,Phone,Performance_Rating,Remote
0,101,Alice,25,Male,HR,50000,2020-01-15,alice@example.com,9876543210,5,Yes
1,102,Bob,26,Female,IT,"₹60,000",15/02/2021,bob@example,(987)-654-3211,4,No
2,103,Charlie,Twenty Seven,Female,Finance,70000,"March 3, 2022",charlie@gmail.com,98765 43212,3,YES
3,104,David,31,Male,Sales,80000,2021/04/01,,+91-9876543213,None,NO
4,105,Eva,None,F,IT,N/A,,None,,Excellent,True
5,106,Frank,28,M,hr,-5000,05-06-2020,frank@yahoo.com,None,2,False
6,107,Grace,45,Female,Finance,120000,None,grace@gmail.com,9876543215,5,yes
7,108,Henry,-5,Male,Marketing,90000,2023-12-11,henry@gmail,98765432,1,no
8,109,Isabella,200,Female,Sales,"₹75,000",11/11/2022,isabella@gmail.com,9876543217,4,Y
9,110,Jack,34,Male,IT,None,2020-07-30,jack@gmail.com,9876543218,,N
10,111,kate,,Female,Finance,65000,2019-05-14,kate@gmail.com,9876543219,3,None
11,112,LUCAS,29,Male,IT,"55,000",2022-13-01,lucas@gmail.com,9876543220,4,
12,113,Mia,30,Female,Marketing,85000,2021-02-28,mia@gmail.com,9876543221,5,True
13,114,Noah,N/A,Unknown,HR,70000,Unknown,noahgmail.com,Unknown,N/A,False
14,115,Olivia,27,Male,Sales,,2024-01-01,olivia@gmail.com,9876543223,2,Yes
15,116,Peter,41,Female,Finance,$95000,2018/09/15,peter@gmail.com,9876543224,4,No
16,117,Quinn,39,M,IT,100000,2020.10.10,quinn@gmail.com,9876543225,5,True
17,118,Rachel,33,F,Marketing,110000,2023/03/07,rachel@gmail.com,9876543226,3,False
18,119,Sam,29,Male,HR,78000,07 Aug 2022,sam@gmail.com,9876543227,2,YES
19,120,Tom,31,Female,Sales,82000,2021-06-18,tom@gmail.com,9876543228,1,NO

In [12]:
gender_map = {
    "F": "Female",
    "M": "Male",
    "Unknown": "Pending"
}

df["Gender"] = df["Gender"].replace(gender_map)

In [14]:
df.head(20)

,Employee_ID,Name,Age,Gender,Department,Salary,Joining_Date,Email,Phone,Performance_Rating,Remote
0,101,Alice,25,Male,HR,50000,2020-01-15,alice@example.com,9876543210,5,Yes
1,102,Bob,26,Female,IT,"₹60,000",15/02/2021,bob@example,(987)-654-3211,4,No
2,103,Charlie,Twenty Seven,Female,Finance,70000,"March 3, 2022",charlie@gmail.com,98765 43212,3,YES
3,104,David,31,Male,Sales,80000,2021/04/01,,+91-9876543213,None,NO
4,105,Eva,None,Female,IT,N/A,,None,,Excellent,True
5,106,Frank,28,Male,hr,-5000,05-06-2020,frank@yahoo.com,None,2,False
6,107,Grace,45,Female,Finance,120000,None,grace@gmail.com,9876543215,5,yes
7,108,Henry,-5,Male,Marketing,90000,2023-12-11,henry@gmail,98765432,1,no
8,109,Isabella,200,Female,Sales,"₹75,000",11/11/2022,isabella@gmail.com,9876543217,4,Y
9,110,Jack,34,Male,IT,None,2020-07-30,jack@gmail.com,9876543218,,N
10,111,kate,,Female,Finance,65000,2019-05-14,kate@gmail.com,9876543219,3,None
11,112,LUCAS,29,Male,IT,"55,000",2022-13-01,lucas@gmail.com,9876543220,4,
12,113,Mia,30,Female,Marketing,85000,2021-02-28,mia@gmail.com,9876543221,5,True
13,114,Noah,N/A,Pending,HR,70000,Unknown,noahgmail.com,Unknown,N/A,False
14,115,Olivia,27,Male,Sales,,2024-01-01,olivia@gmail.com,9876543223,2,Yes
15,116,Peter,41,Female,Finance,$95000,2018/09/15,peter@gmail.com,9876543224,4,No
16,117,Quinn,39,Male,IT,100000,2020.10.10,quinn@gmail.com,9876543225,5,True
17,118,Rachel,33,Female,Marketing,110000,2023/03/07,rachel@gmail.com,9876543226,3,False
18,119,Sam,29,Male,HR,78000,07 Aug 2022,sam@gmail.com,9876543227,2,YES
19,120,Tom,31,Female,Sales,82000,2021-06-18,tom@gmail.com,9876543228,1,NO

In [23]:
df["Salary"] = df["Salary"].str.replace('$', '', regex=False)
df["Salary"] = df["Salary"].str.replace('₹', '', regex=False)

In [24]:
df["Salary"] = df["Salary"].str.replace(',', '', regex=False)

In [31]:
df["Salary"] = df["Salary"].str.replace('N/A', '', regex=False)
df.loc[df["Salary"].isna(), "Salary"] = 0
df["Salary"] = df["Salary"].str.strip()
df["Salary"] = pd.to_numeric(df["Salary"], errors='coerce')
df["Salary"] = df["Salary"].fillna(0)
df["Salary"] = df["Salary"].astype(float)

errors='coerce' tells pandas: "If you encounter anything that isn't a clean number, don't crash—just turn it into a NaN