In [28]:
import numpy as np
import pandas as pd

# Bigger, messier practice dataset
data = {
    "Transaction__ID": [201, 202, 203, 204, 202, 205, 206, 207, 208, 209, 203, 210, 211],
    "Customer_Name": ["john doe", "Jane Smith", "Bob Jones", "Alice Brown", "Jane Smith", "Charlie Green", "EMILY WHITE", "  Tom Clark  ", "Anna Bell", "George Best", "Bob Jones", "Ray Adams", "Sarah Jenkins"],
    "Join_Date": ["2023-01-15", "2023/02/20", "03-12-2023", "2023-04-05", "2023/02/20", "2023-06-18", "2023-07-22", None, "2023-09-01", "2023-10-10", "03-12-2023", "2023-11-15", "2023-12-25"],
    "Product_Category": ["Electronics", "Clothing", "Home", "Electronics", "Clothing", "Home", "ELECTRONICS", "Clothing", "Home", "Electronics", "Home", "Books", "Clothing"],
    "Item_Price": ["$45.00", "22.50", "$120.00", "free", "22.50", "$15.99", "$3000.00", "$12.00", None, "$85.50", "$120.00", "-5.00", "$45.00"],
    "Quantity_Ordered": [1, 2, 1, 1, 2, 3, 1, 5, 2, -4, 1, 1, 1000]
}

# Load into DataFrame
df = pd.DataFrame(data)
print("Dataset Loaded! Shape:", df.shape)

Dataset Loaded! Shape: (13, 6)

In [29]:
df.head(10)

,Transaction__ID,Customer_Name,Join_Date,Product_Category,Item_Price,Quantity_Ordered
0,201,john doe,2023-01-15,Electronics,$45.00,1
1,202,Jane Smith,2023/02/20,Clothing,22.50,2
2,203,Bob Jones,03-12-2023,Home,$120.00,1
3,204,Alice Brown,2023-04-05,Electronics,free,1
4,202,Jane Smith,2023/02/20,Clothing,22.50,2
5,205,Charlie Green,2023-06-18,Home,$15.99,3
6,206,EMILY WHITE,2023-07-22,ELECTRONICS,$3000.00,1
7,207,Tom Clark,None,Clothing,$12.00,5
8,208,Anna Bell,2023-09-01,Home,None,2
9,209,George Best,2023-10-10,Electronics,$85.50,-4

In [39]:
df.drop_duplicates(inplace = True)

In [40]:
df.dropna(inplace = True)

In [44]:
df['Item_Price'] = df['Item_Price'].str.replace('$', '', regex = False)

In [45]:
df['Item_Price'] = df['Item_Price'].astype(float)

Regex is short for Regular Expression.

Think of it as a super-powered "Find and Replace" tool. While a normal search looks for exact matches (like searching for the word "free"), Regex allows you to search for patterns in text instead of exact words.

In [53]:
df.loc[df['Item_Price'].isna(), 'Item_Price'] = 0

In [54]:
df.head()

,Transaction__ID,Customer_Name,Join_Date,Product_Category,Item_Price,Quantity_Ordered
0,201,john doe,2023-01-15,Electronics,45.00,1
1,202,Jane Smith,2023/02/20,Clothing,22.50,2
2,203,Bob Jones,03-12-2023,Home,120.00,1
3,204,Alice Brown,2023-04-05,Electronics,0.00,1
5,205,Charlie Green,2023-06-18,Home,15.99,3

In [55]:
df = df[df["Item_Price"] >= 0]
df = df[df["Quantity_Ordered"] > 0]

In [56]:
df.head()

,Transaction__ID,Customer_Name,Join_Date,Product_Category,Item_Price,Quantity_Ordered
0,201,john doe,2023-01-15,Electronics,45.00,1
1,202,Jane Smith,2023/02/20,Clothing,22.50,2
2,203,Bob Jones,03-12-2023,Home,120.00,1
3,204,Alice Brown,2023-04-05,Electronics,0.00,1
5,205,Charlie Green,2023-06-18,Home,15.99,3

In [57]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'], format='mixed')

In [58]:
df.head()

,Transaction__ID,Customer_Name,Join_Date,Product_Category,Item_Price,Quantity_Ordered
0,201,john doe,2023-01-15,Electronics,45.00,1
1,202,Jane Smith,2023-02-20,Clothing,22.50,2
2,203,Bob Jones,2023-03-12,Home,120.00,1
3,204,Alice Brown,2023-04-05,Electronics,0.00,1
5,205,Charlie Green,2023-06-18,Home,15.99,3

Fix Capitalisation

In [60]:
df['Customer_Name'] = df['Customer_Name'].str.title().str.strip()
# Calitalise first letter and remove trailing spaces

In [61]:
df.head()

,Transaction__ID,Customer_Name,Join_Date,Product_Category,Item_Price,Quantity_Ordered
0,201,John Doe,2023-01-15,Electronics,45.00,1
1,202,Jane Smith,2023-02-20,Clothing,22.50,2
2,203,Bob Jones,2023-03-12,Home,120.00,1
3,204,Alice Brown,2023-04-05,Electronics,0.00,1
5,205,Charlie Green,2023-06-18,Home,15.99,3

In [62]:
df['Product_Category'] = df['Product_Category'].str.title().str.strip()

In [63]:
df.head()

,Transaction__ID,Customer_Name,Join_Date,Product_Category,Item_Price,Quantity_Ordered
0,201,John Doe,2023-01-15,Electronics,45.00,1
1,202,Jane Smith,2023-02-20,Clothing,22.50,2
2,203,Bob Jones,2023-03-12,Home,120.00,1
3,204,Alice Brown,2023-04-05,Electronics,0.00,1
5,205,Charlie Green,2023-06-18,Home,15.99,3