In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 

# Set seed for reproducibility
np.random.seed(42)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 

# Set seed for reproducibility
np.random.seed(42)

# Generate realistic data
n_rows = 180
cities = np.random.choice(["Taipei", "New York", "London"], size=n_rows)
seasons = np.random.choice(["Summer", "Winter"], size=n_rows)
boba_types = np.random.choice(["Classic Milk Tea", "Fruit Tea"], size=n_rows)

# Base temperature depending on city and season
temp = []
for city, season in zip(cities, seasons):
    if season == "Summer":
        temp.append(np.random.normal(30 if city == "Taipei" else 25, 3))
    else:
        temp.append(np.random.normal(15 if city == "Taipei" else 5, 4))

# Base sales depending on temperature, boba type, and city
sales = []
for t, b_type, city in zip(temp, boba_types, cities):
    base = 150 if city == "New York" else (120 if city == "London" else 100)
    # Fruit tea sells incredibly well when it's hot; Milk tea is steady
    if b_type == "Fruit Tea":
        sale_val = base + (t * 4.5) + np.random.normal(0, 15)
    else:
        sale_val = base + 50 + (t * 0.8) + np.random.normal(0, 10)
    sales.append(round(sale_val, 2))

# Create DataFrame
df = pd.DataFrame({
    "City": cities,
    "Season": seasons,
    "Boba_Type": boba_types,
    "Temperature_C": [round(t, 1) for t in temp],
    "Daily_Sales_USD": sales,
    "Customer_Rating": np.random.uniform(3.5, 5.0, size=n_rows).round(1)
})

# Quick preview
(df.head())

,City,Season,Boba_Type,Temperature_C,Daily_Sales_USD,Customer_Rating
0,London,Summer,Classic Milk Tea,18.9,200.65,3.7
1,Taipei,Summer,Fruit Tea,30.6,239.25,4.8
2,London,Winter,Classic Milk Tea,2.4,183.68,3.7
3,London,Summer,Fruit Tea,27.6,245.02,4.1
4,Taipei,Winter,Classic Milk Tea,11.8,180.07,4.7

In [5]:
df.groupby("Boba_Type").median(numeric_only = True)

                  Temperature_C  Daily_Sales_USD  Customer_Rating
Boba_Type
Classic Milk Tea           16.2           186.60              4.3
Fruit Tea                  19.1           204.74              4.1

In [6]:
df.groupby("Boba_Type").min(numeric_only = True)

                  Temperature_C  Daily_Sales_USD  Customer_Rating
Boba_Type
Classic Milk Tea           -1.4           145.55              3.5
Fruit Tea                  -1.9            99.10              3.5

In [7]:
df.groupby("Boba_Type").max(numeric_only = True)

                  Temperature_C  Daily_Sales_USD  Customer_Rating
Boba_Type
Classic Milk Tea           35.3           232.71              5.0
Fruit Tea                  35.6           299.61              4.9

In [11]:
df.groupby("Boba_Type").agg({"Daily_Sales_USD" : ['mean', 'median', 'max', 'min', 'count']})

                 Daily_Sales_USD
                            mean  median     max     min
Boba_Type
Classic Milk Tea      189.380723  186.60  232.71  145.55
Fruit Tea             196.048247  204.74  299.61   99.10

In [14]:
df.groupby("Boba_Type").describe()

                 Temperature_C                                                \
                         count       mean        std  min   25%   50%    75%
Boba_Type
Classic Milk Tea          83.0  16.230120  10.602217 -1.4  6.55  16.2  25.05
Fruit Tea                 97.0  17.378351  10.901426 -1.9  7.70  19.1  27.60

                       Daily_Sales_USD              ...                   \
                   max           count        mean  ...      75%     max
Boba_Type                                           ...
Classic Milk Tea  35.3            83.0  189.380723  ...  205.435  232.71
Fruit Tea         35.6            97.0  196.048247  ...  234.220  299.61

                 Customer_Rating
                           count      mean       std  min  25%  50%  75%  max
Boba_Type
Classic Milk Tea            83.0  4.228916  0.448719  3.5  3.8  4.3  4.6  5.0
Fruit Tea                   97.0  4.193814  0.434649  3.5  3.8  4.1  4.5  4.9

[2 rows x 24 columns]

# Select rows based on column description

In [15]:
df.head()

,City,Season,Boba_Type,Temperature_C,Daily_Sales_USD,Customer_Rating
0,London,Summer,Classic Milk Tea,18.9,200.65,3.7
1,Taipei,Summer,Fruit Tea,30.6,239.25,4.8
2,London,Winter,Classic Milk Tea,2.4,183.68,3.7
3,London,Summer,Fruit Tea,27.6,245.02,4.1
4,Taipei,Winter,Classic Milk Tea,11.8,180.07,4.7

In [22]:
df[(df["Customer_Rating"] == 3.7) & (df["Season"] == "Winter")]

,City,Season,Boba_Type,Temperature_C,Daily_Sales_USD,Customer_Rating
2,London,Winter,Classic Milk Tea,2.4,183.68,3.7
31,London,Winter,Classic Milk Tea,-0.7,160.02,3.7
62,New York,Winter,Fruit Tea,8.3,233.31,3.7
74,New York,Winter,Classic Milk Tea,4.1,203.22,3.7
105,London,Winter,Classic Milk Tea,6.0,180.21,3.7
149,Taipei,Winter,Fruit Tea,15.6,164.09,3.7
160,London,Winter,Fruit Tea,-1.9,115.20,3.7
176,London,Winter,Classic Milk Tea,-1.1,173.88,3.7