In [8]:
import pandas as pd 
import numpy as np

In [9]:
df = pd.read_csv("../CSV Files/Clean_Data.csv")

In [11]:
df.head(20)

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0
15        60     98       120     215.2
16        60    100       120     300.0
17        45     90       112       NaN
18        60    103       123     323.0
19        45     97       125     243.0

Remove Rows
One way to deal with empty cells is to remove rows that contain empty cells.

This is usually OK, since data sets can be very big, and removing a few rows will not have a big impact on the result.

In [15]:
df2 = df.dropna() # Drops the whole row containing null values

In [16]:
df2.head(20)

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0
15        60     98       120     215.2
16        60    100       120     300.0
18        60    103       123     323.0
19        45     97       125     243.0
20        60    108       131     364.2

In [18]:
df.dropna(inplace = True) # Replace in the original dataframe

Replace Empty Values
Another way of dealing with empty cells is to insert a new value instead.

This way you do not have to delete entire rows just because of some empty cells.

The fillna() method allows us to replace empty cells with a value

In [19]:
df3 = pd.read_csv("../CSV Files/Clean_Data.csv")

In [20]:
df.fillna(20, inplace = True)

In [22]:
df.fillna({"Pulse" : 130}, inplace = True)  # Fill only column Pulse with 130

Replace Using Mean, Median, or Mode
A common way to replace empty cells, is to calculate the mean, median or mode value of the column.

Pandas uses the mean() median() and mode() methods to calculate the respective values for a specified column

In [23]:
df4 = pd.read_csv("../CSV Files/Clean_Data.csv")

In [26]:
mean_pulse = df["Pulse"].mean()

In [34]:
df4.fillna({"Pulse" : mean_pulse}, inplace = True) # Same with median and mode

When to use Mode

Suppose you have:

Department
IT
HR
IT
Finance
IT
NaN

Fill the missing value with:

IT

because it appears most frequently.

In [36]:
df.dropna(subset=["Duration"]) # Remove rows with a NULL value in the "Date" column

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[164 rows x 4 columns]