In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("../CSV Files/system_log.csv")

In [3]:
df.head()

    timestamp  gpu_id  latency_ms  gpu_temp_c
0  1719878400       0        24.5        68.2
1  1719878401       0        25.1        68.5
2  1719878402       1        45.8        74.1
3  1719878403       0        23.9        67.9
4  1719878404       1        44.2        73.8

# Selecting a column

In [10]:
print(df["timestamp"])

0    1719878400
1    1719878401
2    1719878402
3    1719878403
4    1719878404
5    1719878405
Name: timestamp, dtype: int64

In [14]:
df["gpu_id"]

0    16.5
1    17.1
2    38.8
3    15.9
4    37.2
5    16.1
Name: gpu_id, dtype: float64

Column Arithmatic

In [16]:
df["gpu_id"] += (df["latency_ms"] - 8.35)

In [17]:
df.head()

    timestamp  gpu_id  latency_ms  gpu_temp_c
0  1719878400   32.65        24.5        68.2
1  1719878401   33.85        25.1        68.5
2  1719878402   76.25        45.8        74.1
3  1719878403   31.45        23.9        67.9
4  1719878404   73.05        44.2        73.8

In [18]:
df["flag"] = df["latency_ms"] < 30
df.head()

    timestamp  gpu_id  latency_ms  gpu_temp_c   flag
0  1719878400   32.65        24.5        68.2   True
1  1719878401   33.85        25.1        68.5   True
2  1719878402   76.25        45.8        74.1  False
3  1719878403   31.45        23.9        67.9   True
4  1719878404   73.05        44.2        73.8  False

In [19]:
del df["timestamp"]  # Delete a whole column

In [20]:
df.head()

   gpu_id  latency_ms  gpu_temp_c   flag
0   32.65        24.5        68.2   True
1   33.85        25.1        68.5   True
2   76.25        45.8        74.1  False
3   31.45        23.9        67.9   True
4   73.05        44.2        73.8  False

In [22]:
gpu_id = df.pop("gpu_id") # Column to series by popping

In [24]:
print(gpu_id)
print(type(gpu_id))

0    32.65
1    33.85
2    76.25
3    31.45
4    73.05
5    31.85
Name: gpu_id, dtype: float64
<class 'pandas.core.series.Series'>

In [25]:
df.head()

   latency_ms  gpu_temp_c   flag
0        24.5        68.2   True
1        25.1        68.5   True
2        45.8        74.1  False
3        23.9        67.9   True
4        44.2        73.8  False

In [26]:
df["gpu_id"] = gpu_id  # Adding once again

In [27]:
df.head()

   latency_ms  gpu_temp_c   flag  gpu_id
0        24.5        68.2   True   32.65
1        25.1        68.5   True   33.85
2        45.8        74.1  False   76.25
3        23.9        67.9   True   31.45
4        44.2        73.8  False   73.05

In [28]:
df["hehe"] = "faa"  # Broadcasted to the whole column

In [29]:
df.head()

   latency_ms  gpu_temp_c   flag  gpu_id hehe
0        24.5        68.2   True   32.65  faa
1        25.1        68.5   True   33.85  faa
2        45.8        74.1  False   76.25  faa
3        23.9        67.9   True   31.45  faa
4        44.2        73.8  False   73.05  faa

doubts: \n
[:2] notation

In [30]:
df.insert(1, "skibidi", "dop")

In [31]:
df.head()

   latency_ms skibidi  gpu_temp_c   flag  gpu_id hehe
0        24.5     dop        68.2   True   32.65  faa
1        25.1     dop        68.5   True   33.85  faa
2        45.8     dop        74.1  False   76.25  faa
3        23.9     dop        67.9   True   31.45  faa
4        44.2     dop        73.8  False   73.05  faa