In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("../CSV Files/adult11.csv")

# iloc
.iloc means:

"Select by integer position."

General form:

df.iloc[rows, columns]

Think of it as

[row selection, column selection]

it also follows zero indexing

In [5]:
df.iloc[2, 2]

np.int64(336951)

In [6]:
df.iloc[1:4, 2]

1     89814
2    336951
3    160323
Name: fnlwgt, dtype: int64

In [7]:
df.iloc[1:4, 2:4]

   fnlwgt     education
1   89814       HS-grad
2  336951    Assoc-acdm
3  160323  Some-college

In [9]:
df.iloc[: , :3]

# rows: all
# columns: first three

       age     workclass  fnlwgt
0       25       Private  226802
1       38       Private   89814
2       28     Local-gov  336951
3       44       Private  160323
4       18             ?  103497
...    ...           ...     ...
48837   27       Private  257302
48838   40       Private  154374
48839   58       Private  151910
48840   22       Private  201490
48841   52  Self-emp-inc  287927

[48842 rows x 3 columns]

In [11]:
df.iloc[::2, ::3]

# every second item from row and every third item from column

       age     education         occupation  gender  hours-per-week
0       25          11th  Machine-op-inspct    Male              40
2       28    Assoc-acdm    Protective-serv    Male              40
4       18  Some-college                  ?  Female              30
6       29       HS-grad                  ?    Male              40
8       24  Some-college      Other-service  Female              40
...    ...           ...                ...     ...             ...
48832   32          10th  Handlers-cleaners    Male              40
48834   32       Masters       Tech-support    Male              11
48836   22  Some-college    Protective-serv    Male              40
48838   40       HS-grad  Machine-op-inspct    Male              40
48840   22       HS-grad       Adm-clerical    Male              20

[24421 rows x 5 columns]

In [12]:
df2 = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)

In [13]:
df2.head()

        one       two     three
a -2.008765  0.169654       NaN
b  0.716287  1.279713  0.781789
c  1.083057  1.550459  1.278351
d       NaN  0.483078  0.573258

In [22]:
row = df2.iloc[1]
print(row)

one      0.716287
two      1.279713
three    0.781789
Name: b, dtype: float64

In [21]:
column = df2["two"]
print(column)

a    0.169654
b    1.279713
c    1.550459
d    0.483078
Name: two, dtype: float64

In [20]:
df2.sub(row, axis="columns")

        one       two     three
a -2.725052 -1.110059       NaN
b  0.000000  0.000000  0.000000
c  0.366770  0.270746  0.496562
d       NaN -0.796635 -0.208531